-- 코드를 작성해주세요
WITH COU AS(
SELECT COUNT(ID) AS CHILD_COUNT, PARENT_ID
FROM ECOLI_DATA
WHERE PARENT_ID IS NOT NULL
GROUP BY PARENT_ID
)

SELECT ID, IF(CHILD_COUNT IS NULL, 0, CHILD_COUNT) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN COU B ON A.ID = B.PARENT_ID
ORDER BY ID
