-- 코드를 입력하세요
SELECT B.PRODUCT_CODE, SUM(A.SALES_AMOUNT * B.PRICE) AS SALES
FROM OFFLINE_SALE A
LEFT JOIN PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SUM(A.SALES_AMOUNT * B.PRICE) DESC, B.PRODUCT_CODE