-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR , MONTH(SALES_DATE) AS MONTH , GENDER AS GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
FROM ONLINE_SALE A
INNER JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE B.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER
