-- 코드를 입력하세요
# SELECT B.ANIMAL_ID, B.NAME
# FROM ANIMAL_OUTS A
# LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE B.DATETIME IS NULL
# ORDER BY ANIMAL_ID

SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A
LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY ANIMAL_ID