
# SELECT A.PRODUCT_ID,PRODUCT_NAME,SUM(PRICE * AMOUNT) AS TOTAL_SALES
# FROM FOOD_ORDER A
# LEFT JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
# WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5 AND 
# ORDER BY TOTAL_SALES DESC, PRODUCT_ID 

SELECT A.PRODUCT_ID,PRODUCT_NAME,SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER A
INNER JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5 
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID 
