# -- 코드를 입력하세요
WITH DURATE AS (
SELECT B.HISTORY_ID, B.CAR_ID, DATEDIFF(end_date, start_date) + 1 AS period, (CASE 
      WHEN DATEDIFF(end_date, start_date) + 1 >= 90 THEN '90일 이상'
      WHEN DATEDIFF(end_date, start_date) + 1 >= 30 THEN '30일 이상'
      WHEN DATEDIFF(end_date, start_date) + 1 >= 7 THEN '7일 이상'
      ELSE 'NONE' END ) AS DT , DAILY_FEE, A.CAR_TYPE
FROM CAR_RENTAL_COMPANY_CAR A
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = "트럭"
    )

SELECT HISTORY_ID, ROUND(period * (DAILY_FEE-(DAILY_FEE * IFNULL(DISCOUNT_RATE/100,0)))) AS FEE
FROM DURATE A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.DT = B.DURATION_TYPE AND A.CAR_TYPE = B.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
