-- 코드를 입력하세요
WITH FIN AS (
SELECT SUM(TOTAL_ORDER) AS TOTAL, FLAVOR
FROM (SELECT SHIPMENT_ID,FLAVOR,TOTAL_ORDER
FROM FIRST_HALF
UNION
SELECT SHIPMENT_ID,FLAVOR,TOTAL_ORDER
FROM JULY) AS A
GROUP BY A.FLAVOR
ORDER BY TOTAL DESC
LIMIT 3 )

SELECT B.FLAVOR
FROM FIRST_HALF A
INNER JOIN FIN B ON A.FLAVOR = B.FLAVOR
