-- 코드를 입력하세요
-- 의사와 예약 테이블 조인 후 날짜를 조회한다
-- 그 다음 환자와 조인해서 출력한다.
SELECT A.APNT_NO,C.PT_NAME,C.PT_NO,B.MCDP_CD,B.DR_NAME,A.APNT_YMD
FROM APPOINTMENT A
INNER JOIN DOCTOR B ON A.MCDP_CD = B.MCDP_CD
INNER JOIN PATIENT C ON A.PT_NO = C.PT_NO
WHERE DATE(A.APNT_YMD) = '2022-04-13' AND A.MCDP_CD = 'CS' AND B.DR_ID = A.MDDR_ID AND A.APNT_CNCL_YMD IS NULL
ORDER BY A.APNT_YMD 
