-- 코드를 작성해주세요
WITH PAR AS(
SELECT B.ITEM_ID
FROM ITEM_INFO A
LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
WHERE A.RARITY = "RARE")

SELECT A.ITEM_ID,	A.ITEM_NAME,	A.RARITY
FROM ITEM_INFO A
LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
WHERE B.PARENT_ITEM_ID IN (SELECT B.ITEM_ID
FROM ITEM_INFO A
LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
WHERE A.RARITY = "RARE")
ORDER BY A.ITEM_ID DESC