-- 코드를 작성해주세요
-- 연도별 높은 수 찾기
WITH LARGE AS (
SELECT MAX(SIZE_OF_COLONY) AS MAXSIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE))
 
#  -- 편차 구하기
# SELECT YEAR(DIFFERENTIATION_DATE), (MAX(SIZE_OF_COLONY)-SIZE_OF_COLONY) AS YEAR_DEV, ID
# FROM ECOLI_DATA 
# GROUP BY YEAR(DIFFERENTIATION_DATE), ID

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (B.MAXSIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA A
LEFT JOIN LARGE B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV
