
SELECT ID,	FISH_NAME, LENGTH
FROM FISH_INFO A
INNER JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE (A.FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
                                FROM FISH_INFO
                                GROUP BY FISH_TYPE
    )
ORDER BY A.ID